name: Release All In One container

on:
  push:
    tags:
      - 'ezreeport-report@*'
      - 'ezreeport-files@*'
      - 'ezreeport-mail@*'
      - 'ezreeport-scheduler@*'
      - 'ezreeport-worker@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'

concurrency:
  group: "release-aio"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Get tags of image âš™ï¸
        id: docker_tags
        run: |
          if ${{ contains(github.ref_name, '-rc.') }}; then
            echo "suffix=-rc" >> $GITHUB_OUTPUT
            echo "tag=rc" >> $GITHUB_OUTPUT
          elif ${{ contains(github.ref_name, '-beta.') }}; then
            echo "suffix=-dev" >> $GITHUB_OUTPUT
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "suffix=" >> $GITHUB_OUTPUT
            echo "tag=stable" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta ğŸ”§
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ezpaarse-project/ezreeport-aio
          tags: |
            type=raw,value={{commit_date 'YYYYMM'}},suffix=${{ steps.docker_tags.outputs.suffix }}
            type=raw,value=${{ steps.docker_tags.outputs.tag }}

      - name: Login to GitHub Container Registry ğŸ”‘
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU âš™ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx âš™ï¸
        uses: docker/setup-buildx-action@v3

      - name: Build and push ğŸšš
        uses: docker/build-push-action@v6
        with:
          push: true
          target: aio
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
