name: Release All In One container

on:
  push:
    tags:
      - 'ezreeport-report@*'
      - 'ezreeport-files@*'
      - 'ezreeport-mail@*'
      - 'ezreeport-scheduler@*'
      - 'ezreeport-worker@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'

concurrency:
  group: "release-aio"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Get tags of image âš™ï¸
        id: docker_tags
        run: |
          #!/usr/bin/env bash
          DATE="$(date +%Y%m)"

          # Define label and suffix by type of pre-release
          SUFFIX=""
          if ${{ contains(github.ref_name, '-rc.') }}; then
            echo "label=rc" >> $GITHUB_OUTPUT

            SUFFIX="-rc"
          elif ${{ contains(github.ref_name, '-beta.') }}; then
            echo "label=dev" >> $GITHUB_OUTPUT

            SUFFIX="-dev"
          else
            echo "tag=stable" >> $GITHUB_OUTPUT
          fi

          # Get latest tag (by type of pre-release)
          git tag -l "ezreeport-aio@${DATE}${SUFFIX}.*" --no-column --sort -v:refname | {
            read latest
            if [[ ! -z $latest ]]; then
              # If tag exists, adds 1 to suffix
              latest_suffix=$(echo $latest | sed 's/.*\.//')
              echo "tag=${DATE}${SUFFIX}.$((${latest_suffix} + 1))" >> $GITHUB_OUTPUT
            else
              # If tag doesn't exists, set suffix to 0
              echo "tag=${DATE}${SUFFIX}.0" >> $GITHUB_OUTPUT
            fi
          }

      - name: Docker meta ğŸ”§
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ezpaarse-project/ezreeport-aio
          tags: |
            type=raw,value=${{ steps.docker_tags.outputs.tag }}
            type=raw,value=${{ steps.docker_tags.outputs.label }}

      - name: Login to GitHub Container Registry ğŸ”‘
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU âš™ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx âš™ï¸
        uses: docker/setup-buildx-action@v3

      - name: Build and push ğŸšš
        uses: docker/build-push-action@v6
        with:
          push: true
          target: aio
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push tag ğŸ”–
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git tag 'ezreeport-aio@${{ steps.docker_tags.outputs.tag }}'
          git push --tags
