name: Release Migration container

on:
  push:
    tags:
      - '@ezreeport/database@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta ğŸ”§
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ezpaarse-project/ezreeport-migrate
          tags: |
            type=match,pattern=^@ezreeport/database@(.+)$,group=1
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=rc,enable=${{ startsWith('refs/heads/rc/', github.ref) }}
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Login to GitHub Container Registry ğŸ”‘
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU âš™ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx âš™ï¸
        uses: docker/setup-buildx-action@v3

      - name: Build and push ğŸšš
        uses: docker/build-push-action@v6
        with:
          push: true
          target: migrate
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
