name: Release Files container

on:
  push:
    tags:
      - 'ezreeport-files@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'
  EZR_IS_DEV: ${{ contains(github.ref_name, 'beta') }}
  EZR_IS_RC: ${{ contains(github.ref_name, 'rc') }}

concurrency:
  group: "release-files"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta ğŸ”§
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ezpaarse-project/ezreeport-files
          tags: |
            type=match,pattern=^ezreeport-files@(.+)$,group=1
            type=raw,value=latest,enable=${{ !env.EZR_IS_DEV && !env.EZR_IS_RC }}
            type=raw,value=rc,enable=${{ env.EZR_IS_RC }}
            type=raw,value=dev,enable=${{ env.EZR_IS_DEV }}

      - name: Login to GitHub Container Registry ğŸ”‘
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU âš™ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx âš™ï¸
        uses: docker/setup-buildx-action@v3

      - name: Build and push ğŸšš
        uses: docker/build-push-action@v6
        with:
          push: true
          target: files
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
