name: Release Vue package

on:
  push:
    tags:
      - '@ezpaarse-project/ezreeport-vue@*'

env:
  HUSKY: 0
  TURBO_UI: 'false'

concurrency:
  group: 'release-vue'
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get tags of package âš™ï¸
        id: npm_tags
        run: |
          if ${{ contains(github.ref_name, '-rc.') }}; then
            echo "tag=rc" >> $GITHUB_OUTPUT
          elif ${{ contains(github.ref_name, '-beta.') }}; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup pnpm âš™ï¸
        uses: pnpm/action-setup@v3

      - name: Setup Node âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies âš™ï¸
        run: pnpm i --frozen-lockfile

      - name: Build package ğŸ”§
        env:
          NODE_ENV: production
        run: pnpm turbo run @ezpaarse-project/ezreeport-vue#build:js

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies ğŸ”
        run: pnpm --filter @ezpaarse-project/ezreeport-vue exec -- npm audit signatures

      - name: Release ğŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm --filter @ezpaarse-project/ezreeport-vue publish --provenance --tag ${{ steps.npm_tags.outputs.tag }} --access public --no-git-checks
